dotenv: .env

priority_fee: "0.75 gwei"

settings:
  gas_limit: "100000000000"

autofetch_sources: true
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  
networks:
  default: sepolia
  sepolia:
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    fee: 500000000000000000
    verify: True
    vrf_coordinator: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
    link_token: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    vrf_wrapper: "0xab18414CD93297B0d12ac29E63Ca20f515b3DB46"

reports:
  exclude_contracts:
    - SafeMath
wallets:
  from_key: ${PRIVATE_KEY}
